<?php
/**
 * Ho_Recurring
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the H&O Commercial License
 * that is bundled with this package in the file LICENSE_HO.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.h-o.nl/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@h-o.com so we can send you a copy immediately.
 *
 * @category    Ho
 * @package     Ho_Recurring
 * @copyright   Copyright © 2015 H&O (http://www.h-o.nl/)
 * @license     H&O Commercial License (http://www.h-o.nl/license)
 * @author      Maikel Koek – H&O <info@h-o.nl>
 */
?>
<?php /** @var Ho_Recurring_Block_Adminhtml_Profile_View_Tabs_UpcomingOrder $this */ ?>
<?php $helper = Mage::helper('core'); ?>

<div class="grid np">
    <div class="hor-scroll">
        <table cellspacing="0" class="data order-tables">
            <col />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <thead>
                <tr class="headings">
                    <th class="no-link"><?php echo $this->helper('sales')->__('Product') ?></th>
                    <th class="no-link"><?php echo $this->helper('sales')->__('Price') ?></th>
                    <th class="no-link"><?php echo $this->helper('sales')->__('Qty') ?></th>
                    <th class="no-link"><?php echo $this->helper('sales')->__('Subtotal') ?></th>
                    <th class="no-link"><span class="nobr"><?php echo $this->helper('sales')->__('Tax Amount') ?></span></th>
                    <th class="no-link"><span class="nobr"><?php echo $this->helper('sales')->__('Tax Percent') ?></span></th>
                    <th class="no-link"><span class="nobr"><?php echo $this->helper('sales')->__('Discount Amount') ?></span></th>
                    <th class="no-link last"><span class="nobr"><?php echo $this->helper('sales')->__('Row Total') ?></span></th>
                </tr>
            </thead>
            <tbody>
            <?php $_items = $this->getAllVisibleItems(); ?>
            <?php $i = 1; foreach ($_items as $_item): ?>
                <?php /** @var Mage_Sales_Model_Quote_Item $_item */ ?>
                <tr class="<?php echo $i%2 ? 'even' : 'odd'; ?>">
                    <td><?php echo $_item->getName(); ?></td>
                    <td><?php echo $helper->formatPrice($_item->getPriceInclTax()); ?></td>
                    <td><?php echo $_item->getQty() * 1; ?></td>
                    <td><?php echo $helper->formatPrice($_item->getRowTotal()); ?></td>
                    <td><?php echo $helper->formatPrice($_item->getTaxAmount()); ?></td>
                    <td><?php echo number_format($_item->getTaxPercent(), 0); ?>%</td>
                    <td><?php echo $helper->formatPrice($_item->getDiscountAmount()); ?></td>
                    <td class="last"><?php echo $helper->formatPrice($_item->getRowTotalInclTax()); ?></td>
                </tr>
            <?php $i++; endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<br />

<div class="box-right entry-edit">
    <div class="entry-edit-head"><h4><?php echo Mage::helper('sales')->__('Totals') ?></h4></div>
    <div id="order-totals" class="order-totals">
        <?php echo $this->getChildHtml('order_totals') ?>
    </div>
</div>

