<?php
/**
 *               _
 *              | |
 *     __ _   _ | | _  _   ___  _ __
 *    / _` | / || || || | / _ \| '  \
 *   | (_| ||  || || || ||  __/| || |
 *    \__,_| \__,_|\__, | \___||_||_|
 *                 |___/
 *
 * Adyen Subscription module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 H&O (http://www.h-o.nl/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>, H&O <info@h-o.nl>
 */

/** @var $this Adyen_Subscription_Block_Catalog_Product_View_Profile */

$_coreHelper = $this->helper('core');
?>
<div class="fieldset giftcard-amount-form">
    <dl>
        <dt>
            <label for="adyen_subscription_profile" class="required"><em>*</em>
                <?php echo Mage::helper('adyen_subscription')->__('Subscription'); ?>
            </label>
        </dt>
        <dd>
            <div class="input-box">
                <ul id="adyen-subscription-profile-list" class="options-list">
                    <?php if ($this->canOrderStandalone()): ?>
                        <li>
                            <label>
                                <input type="radio" id="adyen_subscription_profile_none" name="adyen_subscription_profile"
                                       data-profile-id="none" onchange="profileOptions.reloadPrice()"
                                       class="adyen-subscription-profile-option validate-one-required-by-name" value="none"/>
                                <?php echo $this->__('No subscription') ?>
                            </label>
                            <script type="text/javascript">
                                $('adyen_subscription_profile_none').advaiceContainer = 'adyen_subscription_profile_advice';
                            </script>
                        </li>
                    <?php endif; ?>
                    <?php foreach ($this->getProfileCollection() as $profile): ?>
                    <?php /** @var Adyen_Subscription_Model_Product_Profile $profile */ ?>
                    <?php if (!$profile->getShowOnFrontend()) continue; ?>
                    <li>
                        <label>
                            <input type="radio" id="adyen_subscription_profile_<?php echo  $profile->getId(); ?>"
                                   data-profile-id="<?php echo  $profile->getId(); ?>" onchange="profileOptions.reloadPrice()"
                                   name="adyen_subscription_profile" class="adyen-subscription-profile-option validate-one-required-by-name" value="<?php echo $profile->getId(); ?>"
                                   <?php if($this->isProfileSelected($profile)): ?>checked<?php endif; ?>
                                />
                            <?php echo $profile->getFrontendLabel(); ?> <?php echo $_coreHelper->formatCurrency($profile->getPrice()); ?>
                        </label>
                        <script type="text/javascript">
                            $('adyen_subscription_profile_<?php echo  $profile->getId(); ?>').advaiceContainer = 'adyen_subscription_profile_advice';
                        </script>
                    </li>
                    <?php endforeach; ?>
                </ul>
                <div id="adyen_subscription_profile_advice"></div>
            </div>
        </dd>
    </dl>
</div>
<script>
    Product.ProfileOptions = Class.create();
    Product.ProfileOptions.prototype = {
        initialize: function (config) {
            this.config = config;
            this.reloadPrice();
            document.observe("dom:loaded", this.reloadPrice.bind(this));
        },
        reloadPrice: function () {
            var config = this.config;

            $$('#adyen-subscription-profile-list .adyen-subscription-profile-option').each(function (element) {
                var profileId = element.readAttribute('data-profile-id');

                if (config[profileId]) {
                    var configOptions = config[profileId];

                    if (element.checked) {
                        optionsPrice.addCustomPrices(profileId, configOptions);
                    } else {
                        optionsPrice.addCustomPrices(profileId, {price: 0});
                    }
                    optionsPrice.reload();
                }
            });
        }
    };
    var profileOptions = new Product.ProfileOptions(<?php echo $this->getJsonConfig() ?>);
</script>