<?php
/**
 * Ho_Recurring
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the H&O Commercial License
 * that is bundled with this package in the file LICENSE_HO.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.h-o.nl/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@h-o.com so we can send you a copy immediately.
 *
 * @category  Ho
 * @package   Ho_Recurring
 * @author    Paul Hachmang – H&O <info@h-o.nl>
 * @copyright 2015 Copyright © H&O (http://www.h-o.nl/)
 * @license   H&O Commercial License (http://www.h-o.nl/license)
 */

/** @var $this Ho_Recurring_Block_Adminhtml_Profile_Edit_Info_BillingAgreement */
$_billingAgreementCollection = $this->getBACollection();
$_activeBA = $this->getActiveBA();
?>
<select name="profile[billing_agreement_id]">
    <?php if (! $this->isActiveBAValid()): ?>
        <?php echo $this->__("#%s %s (%s)",
            $_activeBA->getReferenceId(),
            $_activeBA->getAgreementLabel(),
            $_activeBA->getStatusLabel()
        ); ?>
    <?php endif; ?>
    <?php foreach($_billingAgreementCollection as $_billingAgreement): ?>
        <?php /** @var $_billingAgreement Adyen_Payment_Model_Billing_Agreement */ ?>
        <?php $_isSelected = $this->getActiveBA()->getId() == $_billingAgreement->getId(); ?>
        <option value="<?php echo $_billingAgreement->getId(); ?>" <?php if($_isSelected): ?>selected<?php endif; ?>>
            <?php echo $this->__("#%s %s (%s)",
                $_billingAgreement->getReferenceId(),
                $_billingAgreement->getAgreementLabel(),
                $_billingAgreement->getStatusLabel()
            ); ?>
        </option>
    <?php endforeach; ?>
</select>
