<?php
/**
 * Ho_Recurring
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the H&O Commercial License
 * that is bundled with this package in the file LICENSE_HO.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.h-o.nl/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@h-o.com so we can send you a copy immediately.
 *
 * @category    Ho
 * @package     Ho_Recurring
 * @copyright   Copyright © 2015 H&O (http://www.h-o.nl/)
 * @license     H&O Commercial License (http://www.h-o.nl/license)
 * @author      Maikel Koek – H&O <info@h-o.nl>
 */
?>
<?php /* @var Ho_Recurring_Block_Customer_Profiles_View $this */ ?>
<?php $_profile = $this->getProfile(); ?>
<div class="page-title title-buttons recurring-profile-view-header-wrapper">
    <h1 class="heading"><?php echo $this->__('Recurring Profile # %s', $this->escapeHtml($_profile->getId())); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="recurring-profile">
    <div class="info-box recurring-profile-details">
        <h2 class="box-title"><?php echo $this->__('Recurring Profile Information') ?></h2>
        <div class="box-content">
            <table class="info-table">
                <tbody>
                <tr>
                    <th><?php echo $this->__('Reference ID:') ?></th>
                    <td><?php echo $this->escapeHtml($_profile->getId()); ?></td>
                </tr>
                <tr>
                    <th><?php echo $this->__('Status:') ?></th>
                    <td><?php echo ucfirst($_profile->getStatus()); ?></td>
                </tr>
                <tr>
                    <th><?php echo $this->__('Created At:') ?></th>
                    <td><?php echo $this->escapeHtml($_profile->getCreatedAtFormatted()); ?></td>
                </tr>
                <tr>
                    <th><?php echo $this->__('Updated At:') ?></th>
                    <td><?php echo $this->escapeHtml($_profile->getUpdatedAtFormatted()); ?></td>
                </tr>
                <tr>
                    <th><?php echo $this->__('Next Order At:') ?></th>
                    <td><?php echo $this->escapeHtml($_profile->getScheduledAtFormatted()); ?></td>
                </tr>
                <tr>
                    <th><?php echo $this->__('Period:') ?></th>
                    <td><?php echo $this->escapeHtml($_profile->getTermLabel()); ?></td>
                </tr>
                <tr>
                    <th><?php echo $this->__('Billing Agreement:') ?></th>
                    <td><a href="<?php echo $this->getUrl('sales/billing_agreement/view', array('agreement' => $_profile->getBillingAgreementId())); ?>">
                            <?php echo $_profile->getBillingAgreement()->getReferenceId(); ?></a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <?php $pastOrders = $_profile->getOrders(); ?>
    <?php if(count($pastOrders) > 0): ?>
        <?php echo $this->getChildHtml('pager'); ?>
        <h2 class="table-caption"><?php echo $this->__('Past Orders') ?></h2>
        <table class="data-table" id="past-orders-table">
            <col width="1" />
            <col width="1" />
            <col />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <thead>
            <tr>
                <th><span class="nobr"><?php echo $this->__('Order #') ?></span></th>
                <th><?php echo $this->__('Date') ?></th>
                <th><?php echo $this->__('Ship To') ?></th>
                <th><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
                <th><span class="nobr"><?php echo $this->__('Order Status') ?></span></th>
                <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($pastOrders as $order): ?>
                <?php /** @var Mage_Sales_Model_Order $order */ ?>
                <tr>
                    <td><?php echo $order->getIncrementId(); ?></td>
                    <td><span class="nobr"><?php echo $order->getCreatedAtFormated('medium'); ?></span></td>
                    <td><?php echo $order->getShippingAddress()->getName(); ?></td>
                    <td><?php echo $order->formatPrice($order->getGrandTotal()); ?></td>
                    <td><em><?php echo $order->getStatusLabel(); ?></em></td>
                    <td class="a-center">
                        <span class="nobr">
                            <a href="<?php echo $this->getUrl('sales/order/view', array('order_id' => $order->getId())); ?>">
                                <?php echo $this->__('View Order') ?></a>
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('past-orders-table');</script>
    <?php endif; ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Recurring Profiles') ?></a></p>
    </div>
</div>
