<?php
/**
 *               _
 *              | |
 *     __ _   _ | | _  _   ___  _ __
 *    / _` | / || || || | / _ \| '  \
 *   | (_| ||  || || || ||  __/| || |
 *    \__,_| \__,_|\__, | \___||_||_|
 *                 |___/
 *
 * Adyen Subscription module (https://www.adyen.com/)
 *
 * Copyright (c) 2015 H&O (http://www.h-o.nl/)
 * See LICENSE.txt for license details.
 *
 * Author: Adyen <magento@adyen.com>, H&O <info@h-o.nl>
 */

/** @var $this Adyen_Subscription_Block_Adminhtml_Sales_Order_View_Subscription */

$_profileQuoteAdd = $this->getProfileQuoteAdditionalInfo();
$_profile = $this->getProfile();
?>
<div class="box-right">
    <!--Subscription Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo $this->__('Related Profile') ?></h4>
        </div>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Profile ID') ?></label></td>
                <td class="value">
                    <a href="<?php echo $this->getUrl('adyen_subscription/adminhtml_profile/view', ['id' => $this->getProfile()->getId()]); ?>">
                        <strong>#<?php echo $_profile->getIncrementId(); ?></strong>
                    </a>
                </td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('adyen_subscription')->__('Profile Status'); ?></label></td>
                <td class="value">
                    <strong><?php echo $_profile->getStatusLabel($_profile->getStatus());?></strong>
                </td>
            </tr>
            <?php if ($_profileQuoteAdd): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Period Date') ?></label></td>
                <td class="value">
                    <strong><?php echo $_profile->getTermLabel(); ?></strong>
                </td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Schedule Date') ?></label></td>
                <td class="value">
                    <strong><?php echo $_profileQuoteAdd->getScheduledAtFormatted(); ?></strong>
                </td>
            </tr>
            <?php endif; ?>
        </table>
    </div>
</div>
<?php echo $this->getChildHtml(); ?>
