<?php
/**
 * Ho_Recurring
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the H&O Commercial License
 * that is bundled with this package in the file LICENSE_HO.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.h-o.nl/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@h-o.com so we can send you a copy immediately.
 *
 * @category    Ho
 * @package     Ho_Recurring
 * @copyright   Copyright © 2015 H&O (http://www.h-o.nl/)
 * @license     H&O Commercial License (http://www.h-o.nl/license)
 * @author      Maikel Koek – H&O <info@h-o.nl>
 */
?>

<?php /* @var $this Ho_Recurring_Block_Catalog_Product_View_Profile */ ?>
<?php $options = Mage::helper('core')->decorateArray($this->getOptions()); ?>
<?php if (count($options)): ?>
    <div id="catalog_product_composite_configure_fields_profile" class="<?php echo $this->getIsLastFieldset() ? 'last-fieldset' : '' ?>">
        <h4><?php echo Mage::helper('catalog')->__('Profile') ?></h4>
        <div class="product-options">
            <dl>
                <select id="profile-option" name="ho_recurring_profile">
                    <?php foreach ($options as $option) : ?>
                        <?php /** @var Ho_Recurring_Model_Product_Profile $option */ ?>
                        <option value="<?=$option->getId();?>" <?=$this->_isSelected($option->getId()) ? 'selected="selected"' : ''; ?>><?php echo $option->getLabel(); ?></option>
                    <?php endforeach; ?>
                </select>
            </dl>
        </div>
    </div>
<?php endif; ?>
