<?php
/**
 * Ho_Recurring
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the H&O Commercial License
 * that is bundled with this package in the file LICENSE_HO.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.h-o.nl/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@h-o.com so we can send you a copy immediately.
 *
 * @category    Ho
 * @package     Ho_Recurring
 * @copyright   Copyright © 2015 H&O (http://www.h-o.nl/)
 * @license     H&O Commercial License (http://www.h-o.nl/license)
 * @author      Maikel Koek – H&O <info@h-o.nl>
 */
?>
<?php /** @var Ho_Recurring_Block_Adminhtml_Profile_Edit_Tabs_General $this */ ?>
<?php $_order = $this->getOrder(); ?>
<?php $_profile = $this->getProfile(); ?>
<?php $_billingAgreement = $this->getBillingAgreement(); ?>

<div class="box-left">
    <!--General Info-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-general-info"><?php echo Mage::helper('ho_recurring')->__('General Information'); ?></h4>
        </div>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Customer') ?></label></td>
                <td class="value">
                    <a href="<?=$this->getCustomerViewUrl(); ?>" target="_blank"><strong><?=$this->htmlEscape($_order->getCustomerName()); ?></strong></a>
                </td>
            </tr>
            <tr>
                <td class="label"><label><?=Mage::helper('ho_recurring')->__('Status'); ?></label></td>
                <td class="value"><?=$_profile->getStatusLabel();?></td>
            </tr>
            <tr>
                <td class="label"><label><?=Mage::helper('ho_recurring')->__('Created from'); ?></label></td>
                <td class="value"><strong><?=$this->getOrderStoreName(); ?></strong></td>
            </tr>
        </table>
    </div>
</div>
<div class="box-right">
    <!--Profile Info-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-profile-info"><?php echo Mage::helper('ho_recurring')->__('Profile Information'); ?></h4>
        </div>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?=Mage::helper('ho_recurring')->__('Created at'); ?></label></td>
                <td class="value"><strong><?=$_profile->getCreatedAt(); ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?=Mage::helper('ho_recurring')->__('Upcoming shipment'); ?></label></td>
                <td class="value"><strong><?=$_profile->getNextOrderAt(); ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?=Mage::helper('ho_recurring')->__('Term'); ?></label></td>
                <td class="value"><strong><?=$_profile->getTermLabel(); ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?=Mage::helper('ho_recurring')->__('Runs until'); ?></label></td>
                <td class="value"><strong><?=$_profile->getEndsAt(); ?></strong></td>
            </tr>
        </table>
    </div>
</div>
<div class="clear"></div>

<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-billing-address"><?php echo Mage::helper('sales')->__('Billing Address') ?></h4>
        </div>
        <fieldset>
            <address><?php echo $_order->getBillingAddress()->getFormated(true) ?></address>
        </fieldset>
    </div>
</div>
<div class="box-right">
    <!--Shipping Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('sales')->__('Shipping Address') ?></h4>
        </div>
        <fieldset>
            <address><?php echo $_order->getShippingAddress()->getFormated(true) ?></address>
        </fieldset>
    </div>
</div>
<div class="clear"></div>

<div class="box-left">
    <!--Payment Info-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-billing-address"><?=Mage::helper('ho_recurring')->__('Billing Agreement Information'); ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?=Mage::helper('ho_recurring')->__('Reference ID'); ?></label></td>
                    <td class="value"><strong><a href="<?=$this->getBillingAgreementViewUrl();?>" target="_blank">
                                <?=$_billingAgreement->getReferenceId(); ?></a></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?=Mage::helper('ho_recurring')->__('Status'); ?></label></td>
                    <td class="value"><strong><?=$_billingAgreement->getStatusLabel(); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?=Mage::helper('ho_recurring')->__('Method code'); ?></label></td>
                    <td class="value"><strong><?=$_billingAgreement->getMethodCode(); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?=Mage::helper('ho_recurring')->__('Created At'); ?></label></td>
                    <td class="value"><strong><?=$_billingAgreement->getCreatedAt(); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?=Mage::helper('ho_recurring')->__('Label'); ?></label></td>
                    <td class="value"><strong><?=$_billingAgreement->getAgreementLabel(); ?></strong></td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Shipping Info-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-address"><?=Mage::helper('ho_recurring')->__('Shipping &amp; Handling Information'); ?></h4>
        </div>
        <fieldset>
            <?php  if ($_order->getTracksCollection()->count()) : ?>
                <a href="#" id="linkId" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?php echo $this->__('Track Order') ?>"><?php echo $this->__('Track Order') ?></a>
                <br/>
            <?php endif; ?>
            <?php if ($_order->getShippingDescription()): ?>
                <strong><?php echo $this->escapeHtml($_order->getShippingDescription()) ?></strong>

                <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                    <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
                <?php else: ?>
                    <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                <?php endif; ?>
                <?php $_incl = $this->displayShippingPriceInclTax($_order); ?>

                <?php echo $_excl; ?>
                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                <?php endif; ?>
            <?php else: ?>
                <?php echo $this->helper('sales')->__('No shipping information available'); ?>
            <?php endif; ?>
        </fieldset>
    </div>
</div>
