<?php
/**
 * Ho_Recurring
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the H&O Commercial License
 * that is bundled with this package in the file LICENSE_HO.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.h-o.nl/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@h-o.com so we can send you a copy immediately.
 *
 * @category    Ho
 * @package     Ho_Recurring
 * @copyright   Copyright © 2015 H&O (http://www.h-o.nl/)
 * @license     H&O Commercial License (http://www.h-o.nl/license)
 * @author      Maikel Koek – H&O <info@h-o.nl>
 */
?>
<?php /** @var Ho_Recurring_Block_Adminhtml_Profile_Edit_Tabs_Products $this */ ?>
<div class="grid np">
    <div class="hor-scroll">
        <table cellspacing="0" class="data order-tables">
            <col width="1" />
            <col width="100" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <thead>
            <tr class="headings">
                <th><?php echo $this->helper('ho_recurring')->__('SKU') ?></th>
                <th><?php echo $this->helper('ho_recurring')->__('Product') ?></th>
                <th><?php echo $this->helper('ho_recurring')->__('Price') ?></th>
                <th class="a-center"><?php echo $this->helper('ho_recurring')->__('Qty') ?></th>
                <th><?php echo $this->helper('ho_recurring')->__('Row total') ?></th>
                <th><?php echo $this->helper('ho_recurring')->__('Once') ?></th>
                <th><?php echo $this->helper('ho_recurring')->__('Added at') ?></th>
                <th><?php echo $this->helper('ho_recurring')->__('Status') ?></th>
                <th class="last"><?php echo $this->helper('ho_recurring')->__('Action') ?></th>
            </tr>
            </thead>
            <?php $_items = $this->getItemsCollection() ?>
            <?php $i = 1; foreach ($_items as $_item): ?>
                <?php /** @var Ho_Recurring_Model_Profile_Item $_item */ ?>
                <tbody class="<?php echo $i%2 ? 'even' : 'odd'; ?>">
                    <tr>
                        <td><?=$_item->getSku(); ?></td>
                        <td><?=$_item->getName(); ?></td>
                        <td><?=$_item->getPrice(); ?></td>
                        <td><?=$_item->getQty(); ?></td>
                        <td><?=$_item->getRowTotal(); ?></td>
                        <td><?=$_item->getOnce(); ?></td>
                        <td><?=$_item->getCreatedAt(); ?></td>
                        <td><?=$_item->getStatus(); ?></td>
                        <td><?php // @todo Actions ?></td>
                    </tr>
                </tbody>
            <?php $i++; endforeach; ?>
        </table>
    </div>
</div>
<br />
